import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import Link from "next/dist/client/link";
import { LocaleSwitcher } from "@/components/LocaleSwitcher";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className="bg-stone-50">
        <NextIntlClientProvider messages={messages}>
          <nav className="flex items-center justify-between gap-4 px-6 py-3 border-b border-stone-200 font-serif text-sm">
            <div className="flex gap-4">
              <Link
                href={`/${locale}`}
                className="text-stone-700 hover:underline"
              >
                Inicio
              </Link>
              <Link
                href={`/${locale}/registro`}
                className="text-stone-700 hover:underline"
              >
                Registro
              </Link>
            </div>
            <LocaleSwitcher />
          </nav>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
